### ISSUE TITLE
Small program to generate ePub from original Markdown files

### ISSUE THREAD

**Issue by mattbeshara** [BBBalls/hillside_hermitage_archive#4]
Hey!  I hope you're doing well.
This seems like poor timing on my part given I can see you've just yesterday committed a second copy of all of the Markdown files, plus a script to generate an ePub from them using Pandoc, but I thought I'd ping you and let you know that I've been writing a small program to generate an ePub directly from your original Markdown files.  (I should have let you know a couple weeks ago, which was the last time I did any significant work on it, but better late than never I guess.)
If you're interested, take a look at `books/build/out.epub` on the `master` branch of my fork of the repo to see what it looks like at this stage.  The ePub is not as nice as looking it could be (it's missing cover images and proper sections) but all the content is there.  I think it's unlikely that you're familiar with the language I've used to write it, but if you think this approach would be useful, let me know as I'd be happy to continue improving it if you would use it.  I can walk you through installing Roswell and using that to run the program yourself if you like as well.
If you don't think this approach is worthwhile, I'll move the program out to its own repo, as I think the code would be useful for generating other ePub files.  Actually, I should probably do that anyway, to keep separate commit histories for the transcripts and the program.
Thanks!

**Comment by BBBalls** [comment]
Hello,

At the moment I am close to a fairly low effort workflow for maintaining HHA and generating the e-books. I am reluctant to say I am not sure how to incorporate to your program into the workflow I have set up. The technical know how of making something like your program is beyond my skill set, and I appreciate that you have been generous with your knowledge, time and energy.

The move back to using Pandoc flavored markdown is because of the ability to generate quality PDFs utilizing the the ConTeXt extensions. I am able to generate an epub, mobi, azw3, and pdf with a single command based on the pandoc markdown files. There are just some kinks to workout for producing a relatively uniform output between the four book formats. Pandoc markdown can be easily converted to Github Flavored Markdown, so I just need to change the Jekyll Kramdown parser to the GFM parser. I think Jekyll can parse html inputs as well, so I am may move away from utilizing markdown for the content on HAA, but instead utilize the pandoc html outputs. Ounce I finish fine tuning the conversion parameters I think I will only have to maintain the Pandoc markdown files.

A program called Pandocomatic looks like it might be useful for automating the use of Pandoc even further, but I haven't had the time to investigate how to utilize it yet. https://heerdebeer.org/Software/markdown/pandocomatic/

Best regards

**Comment by mattbeshara** [comment]
No worries, if you've already got a plan in place to make this project easy to maintain over the long term, then the program wouldn't be able to add much anyway.  Thanks again!
